import "@/shared/styles/globals.css";
import { Header } from "@/widgets/header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen gap-4">
        <Header />
        <main className="container flex-grow mx-[auto] w-full ">
          {children}
        </main>
      </body>
    </html>
  );
}
